export const ADDING_DAMAGE = 'ADDING_DAMAGE';
export const REMOVING_DAMAGE = 'REMOVING_DAMAGE';

export const UPDATED_CHARACTER = 'UPDATED_CHARACTER';

export const SAVING_CHARACTER = 'SAVING_CHARACTER';
export const ADDED_CHARACTER = 'ADDED_CHARACTER';

export const REMOVING_CHARACTER = 'REMOVING_CHARACTER';
export const REMOVED_CHARACTER = 'REMOVED_CHARACTER';

export const LOADING = 'LOADING';
export const LOADED = 'LOADED';